Portfolio: Milestone6: Accessibility
zieeco/portfolio pull request #9
Opened 2021-07-20 17:17 UTC by aliabbani

## 
In this milestone we:

- checked all the points 
- Page titles: we edited the page title.
- Image text alternatives: we edited all the alt attributes.
- Text headings: we follow the rule of the page heading.
- Color contrast: no issues found
- Resize: no issues found
- Interaction: no issues were found
- Moving content: no issues found
- Multimedia: no issues found
- The basic structure of the page: we also edited the form section

2021-07-20 18:10 UTC, Emmyn5600 requested changes
## STATUS: Changes Requested :recycle:

Hi @zieeco 

Good job so far!:clap::clap:
You have done well in implementing the project requirements :clap:, However, there are some issues that you still need to work on to go to the next project but you are almost there!:muscle:

##  Required Changes:writing_hand:

**_Check the comments under the review._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-20 18:10 UTC, Emmyn5600 commented on index.html
>        </textarea>
- [ ] Kindly, fix your contact form, it allows me to send empty message. please make it required.

2021-07-20 18:10 UTC, Emmyn5600 commented on index.html
>      <div class="bottom-line"></div>
- [ ] Please double check the color contrast of the project. Use this [link](https://www.aditus.io/button-contrast-checker/) to check for the color contrast and fix it.

2021-07-20 18:10 UTC, Emmyn5600 commented on index.html
>      </p>
- [ ] Some of the colors you've chosen for your portfolio currently don't meet WebAIM accessibility standards for contrast ratio. Please readjust your color palette by using a color contrast validator tool like this [one](https://color.a11y.com/%5C)  to assess contrast ratio.

2021-07-21 09:48 UTC, carlos-ssh approved these changes
Hi @zieeco, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-21 09:53 UTC, merged